/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import view.*;
import classes.Ticket;
import classes.TicketNivelPrioridade;
import dao.TicketDAO;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author ERNANI
 */
public class UC_Abrir_Atendimento extends javax.swing.JInternalFrame {

    private String ID;

    /**
     * Creates new form UC_Abrir_Atendimento
     */
    public UC_Abrir_Atendimento() {
        initComponents();
        
        TicketDAO td = new TicketDAO();
        List<TicketNivelPrioridade> niveis = td.listarNiveis();
        
        Cbx_Nivel.removeAll();
        for(TicketNivelPrioridade n: niveis) {
           Cbx_Nivel.addItem(n);
        }
    }
    
    public UC_Abrir_Atendimento(String id) {
        initComponents();
        this.ID = id;
        
        TicketDAO td = new TicketDAO();
        List<TicketNivelPrioridade> niveis = td.listarNiveis();
        
        Cbx_Nivel.removeAll();
        for(TicketNivelPrioridade n: niveis) {
           Cbx_Nivel.addItem(n);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt_Titulo = new javax.swing.JTextField();
        TxtArea_Descricao = new javax.swing.JScrollPane();
        Txt_Area_Descricao = new javax.swing.JTextArea();
        Btn_Enviar = new javax.swing.JButton();
        Lbl_Nivel = new javax.swing.JLabel();
        Lbl_Titulo = new javax.swing.JLabel();
        Cbx_Nivel = new javax.swing.JComboBox();
        Lbl_Descricao = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Abrir atendimento");
        setToolTipText("");

        Txt_Area_Descricao.setColumns(20);
        Txt_Area_Descricao.setRows(5);
        TxtArea_Descricao.setViewportView(Txt_Area_Descricao);
        Txt_Area_Descricao.getAccessibleContext().setAccessibleName("TxtArea_Descricao");

        Btn_Enviar.setText("Enviar");
        Btn_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarActionPerformed(evt);
            }
        });

        Lbl_Nivel.setText("Nivel de prioridade:");

        Lbl_Titulo.setText("Titulo do atendimento");

        Lbl_Descricao.setText("Descrição do atendimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtArea_Descricao)
                            .addComponent(Txt_Titulo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbl_Nivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cbx_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(Btn_Enviar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbl_Titulo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_Descricao)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtArea_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Enviar)
                    .addComponent(Cbx_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Nivel))
                .addGap(11, 11, 11))
        );

        Txt_Titulo.getAccessibleContext().setAccessibleName("Txt_Titulo");
        Btn_Enviar.getAccessibleContext().setAccessibleName("Btn_Enviar");
        Lbl_Nivel.getAccessibleContext().setAccessibleName("Lbl_Descricao");
        Lbl_Titulo.getAccessibleContext().setAccessibleName("Lbl_Titulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarActionPerformed
        //Chama classes que precisamos
        Ticket t = new Ticket();
        TicketDAO td = new TicketDAO();
       
        if(Txt_Titulo.getText().isEmpty() || Txt_Area_Descricao.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Favor preencha todos os campos!");
        } else {
            //Carrega os objetos
            t.setTitulo(Txt_Titulo.getText());
            t.setDescricao(Txt_Area_Descricao.getText());
            TicketNivelPrioridade tn = (TicketNivelPrioridade) Cbx_Nivel.getSelectedItem();
            t.setNivel(tn.getId());
            t.setSituacao(1);
            t.setCliente(Integer.parseInt(ID));
            
            //Executa consulta
            td.abrirChamado(t);

            //Limpa campos apos o envio dos dados
            Txt_Titulo.setText("");
            Txt_Area_Descricao.setText("");
        }
    }//GEN-LAST:event_Btn_EnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Enviar;
    private javax.swing.JComboBox Cbx_Nivel;
    private javax.swing.JLabel Lbl_Descricao;
    private javax.swing.JLabel Lbl_Nivel;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JScrollPane TxtArea_Descricao;
    private javax.swing.JTextArea Txt_Area_Descricao;
    private javax.swing.JTextField Txt_Titulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
