/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import classes.TicketNivelPrioridade;
import classes.Usuario;
import dao.TicketDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import view.*;

/**
 *
 * @author ERNANI
 */
public class UC_Acompanhar_Atendimento extends javax.swing.JInternalFrame {

    private String ID;

    /**
     * Creates new form UC_Acompanhar_Atendimento
     */
    public UC_Acompanhar_Atendimento() {
        initComponents();
        
        TicketDAO td = new TicketDAO();
        List<TicketNivelPrioridade> situacao = td.listarSituacao();
        
        Cbx_Situacao.removeAll();
        for(TicketNivelPrioridade s: situacao ) {
           Cbx_Situacao.addItem(s);
        }
    }
    
    public UC_Acompanhar_Atendimento(String id) {
        initComponents();
        
        ID = id;
        
        TicketDAO td = new TicketDAO();
        List<TicketNivelPrioridade> situacao  = td.listarSituacao();
        
        Cbx_Situacao.removeAll();
        for(TicketNivelPrioridade s: situacao) {
           Cbx_Situacao.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Filtros = new javax.swing.JPanel();
        Txt_Pesquisa = new javax.swing.JTextField();
        Btn_Pesquisa = new javax.swing.JButton();
        Cbx_Situacao = new javax.swing.JComboBox();
        Lbl_Situacao = new javax.swing.JLabel();
        Lbl_Descricao = new javax.swing.JLabel();
        Txt_Data_Inicio = new javax.swing.JFormattedTextField();
        Txt_Data_Final = new javax.swing.JFormattedTextField();
        Lbl_Data_Inicio = new javax.swing.JLabel();
        Lbl_Data_Final = new javax.swing.JLabel();
        JP_Atendimentos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Tickets = new javax.swing.JTable();
        Btn_Abrir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Acompanhar atendimentos");

        JP_Filtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        Btn_Pesquisa.setText("Pesquisar");
        Btn_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PesquisaActionPerformed(evt);
            }
        });

        Lbl_Situacao.setText("Situação");

        Lbl_Descricao.setText("Descrição do atendimento");

        try {
            Txt_Data_Inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            Txt_Data_Final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Lbl_Data_Inicio.setText("Data Inicial");

        Lbl_Data_Final.setText("Data Final");

        javax.swing.GroupLayout JP_FiltrosLayout = new javax.swing.GroupLayout(JP_Filtros);
        JP_Filtros.setLayout(JP_FiltrosLayout);
        JP_FiltrosLayout.setHorizontalGroup(
            JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_FiltrosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Data_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGroup(JP_FiltrosLayout.createSequentialGroup()
                        .addComponent(Lbl_Data_Inicio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Data_Final, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Data_Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cbx_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Situacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_FiltrosLayout.createSequentialGroup()
                        .addComponent(Txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Pesquisa))
                    .addComponent(Lbl_Descricao))
                .addGap(16, 16, 16))
        );
        JP_FiltrosLayout.setVerticalGroup(
            JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_FiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Situacao)
                    .addComponent(Lbl_Descricao)
                    .addComponent(Lbl_Data_Inicio)
                    .addComponent(Lbl_Data_Final))
                .addGap(9, 9, 9)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbx_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Pesquisa)
                    .addComponent(Txt_Data_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Data_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Txt_Pesquisa.getAccessibleContext().setAccessibleName("Txt_Pesquisar");
        Btn_Pesquisa.getAccessibleContext().setAccessibleName("Btn_Pesquisar");
        Cbx_Situacao.getAccessibleContext().setAccessibleName("Cbx_Situacao");
        Lbl_Situacao.getAccessibleContext().setAccessibleName("Lbl_Situacao");
        Lbl_Descricao.getAccessibleContext().setAccessibleName("Lbl_Descricao");
        Txt_Data_Inicio.getAccessibleContext().setAccessibleName("Txt_Data_Inicial");
        Txt_Data_Final.getAccessibleContext().setAccessibleName("Txt_Data_Final");
        Lbl_Data_Inicio.getAccessibleContext().setAccessibleName("Lbl_Data_Inicial");
        Lbl_Data_Final.getAccessibleContext().setAccessibleName("Lbl_Data_Final");

        JP_Atendimentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Atendimentos"));

        Tb_Tickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ticket", "Titulo", "Data", "Técnico", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tb_Tickets);

        javax.swing.GroupLayout JP_AtendimentosLayout = new javax.swing.GroupLayout(JP_Atendimentos);
        JP_Atendimentos.setLayout(JP_AtendimentosLayout);
        JP_AtendimentosLayout.setHorizontalGroup(
            JP_AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_AtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        JP_AtendimentosLayout.setVerticalGroup(
            JP_AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_AtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Btn_Abrir.setText("Abrir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JP_Filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_Atendimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_Filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JP_Atendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Abrir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Btn_Abrir.getAccessibleContext().setAccessibleName("Btn_Abrir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PesquisaActionPerformed
        Usuario usu = new Usuario();
        TicketDAO td = new TicketDAO();
        
        usu.setId(Integer.parseInt(this.ID));
        ResultSet rs = td.listarChamadosCliente(usu);
       
        DefaultTableModel model  = (DefaultTableModel) Tb_Tickets.getModel();
        model.setRowCount(0);
        try {
            while(rs.next()) {
                model.addRow(new String[]{ rs.getString("ID"), rs.getString("TITULO"), rs.getString("DATA_ABERTURA"), rs.getString("TECNICO"), rs.getString("SITUACAO")});
            }
        } catch (SQLException e) {
            System.out.println("Erro: "+e.getMessage());;
        }
    }//GEN-LAST:event_Btn_PesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Abrir;
    private javax.swing.JButton Btn_Pesquisa;
    private javax.swing.JComboBox Cbx_Situacao;
    private javax.swing.JPanel JP_Atendimentos;
    private javax.swing.JPanel JP_Filtros;
    private javax.swing.JLabel Lbl_Data_Final;
    private javax.swing.JLabel Lbl_Data_Inicio;
    private javax.swing.JLabel Lbl_Descricao;
    private javax.swing.JLabel Lbl_Situacao;
    private javax.swing.JTable Tb_Tickets;
    private javax.swing.JFormattedTextField Txt_Data_Final;
    private javax.swing.JFormattedTextField Txt_Data_Inicio;
    private javax.swing.JTextField Txt_Pesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
