/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.admin;

import classes.Ticket;
import view.*;
import classes.TicketNivelPrioridade;
import classes.Usuario;
import dao.NivelPrioridadeDAO;
import dao.TicketDAO;
import dao.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.*;

/**
 *
 * @author ERNANI
 */
public class UC_Cadastro_Nivel_Adm extends javax.swing.JInternalFrame {

    private String ID;

    /**
     * Creates new form UC_Acompanhar_Atendimento
     */
    public UC_Cadastro_Nivel_Adm() {
        initComponents();
        
        UsuarioDAO use = new UsuarioDAO();
        List<TicketNivelPrioridade> situacao = use.listarSituacao();
        List<TicketNivelPrioridade> perfil = use.listarPerfil();
        
      
    }
    
    public UC_Cadastro_Nivel_Adm(String id) {
        initComponents();
        
        ID = id;
        
        UsuarioDAO use = new UsuarioDAO();
        List<TicketNivelPrioridade> situacao = use.listarSituacao();
        List<TicketNivelPrioridade> perfil = use.listarPerfil();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt_Descricao = new javax.swing.JTextField();
        Lbl_Nome_Cadastro = new javax.swing.JLabel();
        Btn_Cadastro = new javax.swing.JButton();
        Btn_Alterar = new javax.swing.JButton();
        Btn_Excluir = new javax.swing.JButton();
        Btn_Limpar_Campos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Niveis = new javax.swing.JTable();
        Btn_Abrir1 = new javax.swing.JButton();
        Btn_Abrir2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Niveis de Prioridade");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Niveis de Prioridade"));

        Lbl_Nome_Cadastro.setText("Descrição");

        Btn_Cadastro.setText("Cadastrar");
        Btn_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CadastroActionPerformed(evt);
            }
        });

        Btn_Alterar.setText("Alterar");
        Btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlterarActionPerformed(evt);
            }
        });

        Btn_Excluir.setText("Excluir");
        Btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExcluirActionPerformed(evt);
            }
        });

        Btn_Limpar_Campos.setText("Limpar Campo");
        Btn_Limpar_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Limpar_CamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Nome_Cadastro)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Btn_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Btn_Limpar_Campos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Btn_Excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Btn_Alterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Txt_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Lbl_Nome_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cadastro)
                    .addComponent(Btn_Alterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Excluir)
                    .addComponent(Btn_Limpar_Campos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Niveis de Prioridade"));

        Tb_Niveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tb_Niveis);

        Btn_Abrir1.setText("Pesquisar");
        Btn_Abrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Abrir1ActionPerformed(evt);
            }
        });

        Btn_Abrir2.setText("Abrir");
        Btn_Abrir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Abrir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_Abrir2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Abrir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Abrir1)
                    .addComponent(Btn_Abrir2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Abrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Abrir1ActionPerformed
            
        NivelPrioridadeDAO nv = new NivelPrioridadeDAO();
        ResultSet rs = nv.listaNivel();

        DefaultTableModel model  = (DefaultTableModel) Tb_Niveis.getModel();
        model.setRowCount(0);
        try {
            while(rs.next()) {
                model.addRow(new String[]{ rs.getString("ID"), rs.getString("DESCRICAO")});
            }
        } catch (SQLException e) {
            System.out.println("Erro: "+e.getMessage());
        }
    }//GEN-LAST:event_Btn_Abrir1ActionPerformed

    private void Btn_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CadastroActionPerformed
       
        TicketNivelPrioridade tn = new TicketNivelPrioridade();
        NivelPrioridadeDAO nv = new NivelPrioridadeDAO();
            
        if(Txt_Descricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preecha todos os campos!");
        } else {
            
            tn.setDescricao(Txt_Descricao.getText());

            nv.cadastroNivel(tn);
            Txt_Descricao.setText("");
            
        }
    }//GEN-LAST:event_Btn_CadastroActionPerformed

    private void Btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlterarActionPerformed
        TicketNivelPrioridade tn = new TicketNivelPrioridade();
        NivelPrioridadeDAO nv = new NivelPrioridadeDAO();
            
        if(Txt_Descricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor selecione e carregue um nivel de prioridade em tela!");
        } else {
            String li = String.valueOf(Tb_Niveis.getValueAt(Tb_Niveis.getSelectedRow(), Tb_Niveis.getSelectedColumn()));
        
            int res = JOptionPane.showConfirmDialog(null, "Deseja alterar a descrição do nivel de prioridade?", "Alterar nivel", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {

                tn.setId(Integer.parseInt(li));
                tn.setDescricao(Txt_Descricao.getText());

                nv.alteraNivel(tn);
                Txt_Descricao.setText("");
            } 
        } 
   
    }//GEN-LAST:event_Btn_AlterarActionPerformed

    private void Btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExcluirActionPerformed
         TicketNivelPrioridade tn = new TicketNivelPrioridade();
        NivelPrioridadeDAO nv = new NivelPrioridadeDAO();
            
        if(Txt_Descricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor selecione e carregue um nivel de prioridade em tela!");
        } else {
            String li = String.valueOf(Tb_Niveis.getValueAt(Tb_Niveis.getSelectedRow(), Tb_Niveis.getSelectedColumn()));
        
            int res = JOptionPane.showConfirmDialog(null, "Deseja excluir o nivel de prioridade?", "Excluir nivel", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {

                tn.setId(Integer.parseInt(li));
                nv.deletaNivel(tn);
                Txt_Descricao.setText("");
            } 
        } 
    }//GEN-LAST:event_Btn_ExcluirActionPerformed

    private void Btn_Limpar_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Limpar_CamposActionPerformed
       Txt_Descricao.setText("");
    }//GEN-LAST:event_Btn_Limpar_CamposActionPerformed

    private void Btn_Abrir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Abrir2ActionPerformed
        TicketNivelPrioridade tn = new TicketNivelPrioridade();
        NivelPrioridadeDAO nv = new NivelPrioridadeDAO();
        
        String li = String.valueOf(Tb_Niveis.getValueAt(Tb_Niveis.getSelectedRow(), Tb_Niveis.getSelectedColumn()));
        tn.setId(Integer.parseInt(li));
        
        try {
            ResultSet rs = nv.nivel(tn);
            if(rs.next()) {
                Txt_Descricao.setText(rs.getString("DESCRICAO")); 
            }    
        } catch (SQLException e) {
            System.out.println("Erro ao listar usuario: "+e.getMessage());
        }
    }//GEN-LAST:event_Btn_Abrir2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Abrir1;
    private javax.swing.JButton Btn_Abrir2;
    private javax.swing.JButton Btn_Alterar;
    private javax.swing.JButton Btn_Cadastro;
    private javax.swing.JButton Btn_Excluir;
    private javax.swing.JButton Btn_Limpar_Campos;
    private javax.swing.JLabel Lbl_Nome_Cadastro;
    private javax.swing.JTable Tb_Niveis;
    private javax.swing.JTextField Txt_Descricao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
