/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.admin;

import classes.Ticket;
import view.*;
import classes.TicketNivelPrioridade;
import classes.Usuario;
import dao.TicketDAO;
import dao.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import view.*;

/**
 *
 * @author ERNANI
 */
public class UC_Cadastro_Usuario_Adm extends javax.swing.JInternalFrame {

    private String ID;

    /**
     * Creates new form UC_Acompanhar_Atendimento
     */
    public UC_Cadastro_Usuario_Adm() {
        initComponents();
        
        UsuarioDAO use = new UsuarioDAO();
        List<TicketNivelPrioridade> situacao = use.listarSituacao();
        
        Cbx_Situacao.removeAll();
        for(TicketNivelPrioridade s: situacao ) {
           Cbx_Situacao.addItem(s);
        }
    }
    
    public UC_Cadastro_Usuario_Adm(String id) {
        initComponents();
        
        ID = id;
        
        UsuarioDAO use = new UsuarioDAO();
        List<TicketNivelPrioridade> situacao = use.listarSituacao();
        
        Cbx_Situacao.removeAll();
        for(TicketNivelPrioridade s: situacao ) {
           Cbx_Situacao.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Filtros = new javax.swing.JPanel();
        Txt_Usuario = new javax.swing.JTextField();
        Btn_Pesquisa = new javax.swing.JButton();
        Cbx_Situacao = new javax.swing.JComboBox();
        Lbl_Situacao = new javax.swing.JLabel();
        Lbl_Usuario = new javax.swing.JLabel();
        JP_Atendimentos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Usuarios = new javax.swing.JTable();
        Btn_Abrir1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Txt_Nome_Cadastro = new javax.swing.JTextField();
        Lbl_Nome_Cadastro = new javax.swing.JLabel();
        Lbl_Usuario_Cadastro = new javax.swing.JLabel();
        Txt_Usuario_Cadastro = new javax.swing.JTextField();
        Lbl_Senha_Cadastro = new javax.swing.JLabel();
        Txt_Senha_Cadastro = new javax.swing.JTextField();
        Lbl_Situacao_Cadastro = new javax.swing.JLabel();
        Cbx_Situacao_Cadastro = new javax.swing.JComboBox();
        Lbl_Perfil_Cadastro = new javax.swing.JLabel();
        Cbx_Perfil_Cadastro = new javax.swing.JComboBox();
        Btn_Cadastro = new javax.swing.JButton();
        Btn_Alterar = new javax.swing.JButton();
        Btn_Excluir = new javax.swing.JButton();
        Btn_Limpar_Campos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Usuários");

        JP_Filtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        Btn_Pesquisa.setText("Pesquisar");
        Btn_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PesquisaActionPerformed(evt);
            }
        });

        Lbl_Situacao.setText("Situação");

        Lbl_Usuario.setText("Usuário");

        javax.swing.GroupLayout JP_FiltrosLayout = new javax.swing.GroupLayout(JP_Filtros);
        JP_Filtros.setLayout(JP_FiltrosLayout);
        JP_FiltrosLayout.setHorizontalGroup(
            JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_FiltrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Usuario))
                .addGap(11, 11, 11)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_FiltrosLayout.createSequentialGroup()
                        .addComponent(Cbx_Situacao, 0, 125, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Pesquisa))
                    .addGroup(JP_FiltrosLayout.createSequentialGroup()
                        .addComponent(Lbl_Situacao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JP_FiltrosLayout.setVerticalGroup(
            JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_FiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Usuario)
                    .addComponent(Lbl_Situacao))
                .addGap(6, 6, 6)
                .addGroup(JP_FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Pesquisa)
                    .addComponent(Cbx_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Txt_Usuario.getAccessibleContext().setAccessibleName("Txt_Pesquisar");
        Btn_Pesquisa.getAccessibleContext().setAccessibleName("Btn_Pesquisar");
        Cbx_Situacao.getAccessibleContext().setAccessibleName("Cbx_Situacao");
        Lbl_Situacao.getAccessibleContext().setAccessibleName("Lbl_Situacao");
        Lbl_Usuario.getAccessibleContext().setAccessibleName("Lbl_Descricao");

        JP_Atendimentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Atendimentos"));

        Tb_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuário", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tb_Usuarios);

        javax.swing.GroupLayout JP_AtendimentosLayout = new javax.swing.GroupLayout(JP_Atendimentos);
        JP_Atendimentos.setLayout(JP_AtendimentosLayout);
        JP_AtendimentosLayout.setHorizontalGroup(
            JP_AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_AtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        JP_AtendimentosLayout.setVerticalGroup(
            JP_AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_AtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        Btn_Abrir1.setText("Abrir");
        Btn_Abrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Abrir1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuário"));

        Lbl_Nome_Cadastro.setText("Nome");

        Lbl_Usuario_Cadastro.setText("Usuário");

        Lbl_Senha_Cadastro.setText("Senha");

        Lbl_Situacao_Cadastro.setText("Situação");

        Lbl_Perfil_Cadastro.setText("Perfil");

        Btn_Cadastro.setText("Cadastrar");
        Btn_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CadastroActionPerformed(evt);
            }
        });

        Btn_Alterar.setText("Alterar");
        Btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlterarActionPerformed(evt);
            }
        });

        Btn_Excluir.setText("Excluir");
        Btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExcluirActionPerformed(evt);
            }
        });

        Btn_Limpar_Campos.setText("Limpar Campos");
        Btn_Limpar_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Limpar_CamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_Perfil_Cadastro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Limpar_Campos, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cbx_Perfil_Cadastro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txt_Senha_Cadastro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Usuario_Cadastro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Nome_Cadastro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbx_Situacao_Cadastro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lbl_Senha_Cadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Usuario_Cadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Nome_Cadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Situacao_Cadastro, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Lbl_Nome_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Nome_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Usuario_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Usuario_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Senha_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Senha_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_Perfil_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cbx_Perfil_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Lbl_Situacao_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cbx_Situacao_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cadastro)
                    .addComponent(Btn_Alterar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Excluir)
                    .addComponent(Btn_Limpar_Campos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JP_Filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JP_Atendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(728, 728, 728)
                        .addComponent(Btn_Abrir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JP_Filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JP_Atendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Abrir1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PesquisaActionPerformed
        Usuario u = new Usuario();
        UsuarioDAO td = new UsuarioDAO();

        if(Txt_Usuario.getText().isEmpty()) {

            TicketNivelPrioridade s = (TicketNivelPrioridade) Cbx_Situacao.getSelectedItem();
            u.setSituacao(s.getId());
            ResultSet rs = td.listaUsuariosPorSituacao(u);

            DefaultTableModel model  = (DefaultTableModel) Tb_Usuarios.getModel();
            model.setRowCount(0);
            try {
                while(rs.next()) {
                    model.addRow(new String[]{ rs.getString("ID"), rs.getString("USUARIO"), rs.getString("SITUACAO")});
                }
            } catch (SQLException e) {
                System.out.println("Erro: "+e.getMessage());
            }

        } else {

            

        }

    }//GEN-LAST:event_Btn_PesquisaActionPerformed

    private void Btn_Abrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Abrir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Abrir1ActionPerformed

    private void Btn_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CadastroActionPerformed

    private void Btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AlterarActionPerformed

    private void Btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ExcluirActionPerformed

    private void Btn_Limpar_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Limpar_CamposActionPerformed
        Txt_Nome_Cadastro.setText("");
        Txt_Usuario_Cadastro.setText("");
        Txt_Senha_Cadastro.setText("");
    }//GEN-LAST:event_Btn_Limpar_CamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Abrir1;
    private javax.swing.JButton Btn_Alterar;
    private javax.swing.JButton Btn_Cadastro;
    private javax.swing.JButton Btn_Excluir;
    private javax.swing.JButton Btn_Limpar_Campos;
    private javax.swing.JButton Btn_Pesquisa;
    private javax.swing.JComboBox Cbx_Perfil_Cadastro;
    private javax.swing.JComboBox Cbx_Situacao;
    private javax.swing.JComboBox Cbx_Situacao_Cadastro;
    private javax.swing.JPanel JP_Atendimentos;
    private javax.swing.JPanel JP_Filtros;
    private javax.swing.JLabel Lbl_Nome_Cadastro;
    private javax.swing.JLabel Lbl_Perfil_Cadastro;
    private javax.swing.JLabel Lbl_Senha_Cadastro;
    private javax.swing.JLabel Lbl_Situacao;
    private javax.swing.JLabel Lbl_Situacao_Cadastro;
    private javax.swing.JLabel Lbl_Usuario;
    private javax.swing.JLabel Lbl_Usuario_Cadastro;
    private javax.swing.JTable Tb_Usuarios;
    private javax.swing.JTextField Txt_Nome_Cadastro;
    private javax.swing.JTextField Txt_Senha_Cadastro;
    private javax.swing.JTextField Txt_Usuario;
    private javax.swing.JTextField Txt_Usuario_Cadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
